- easylistspanish/easylistspanish_whitelist.txt
https://forums.lanik.us/viewtopic.php?f=103&t=38545
> P: http://www.todo-publicidad.com/

- easylistspanish/easylistspanish_specific_block.txt
https://forums.lanik.us/viewtopic.php?p=126599#p126599
> A: https://www.elotrolado.net/

- easylistspanish/easylistspanish_general_block.txt
https://forums.lanik.us/viewtopic.php?f=103&t=38816
> A: http://www.eldiarioalerta.com/

- easylistspanish/easylistspanish_general_block_popup.txt
- blocked the [**propellerads**](https://forums.lanik.us/viewtopic.php?f=62&t=37414) popup (e.g http://i.imgur.com/AYELAZ7.png)
- removed the unnecessary comment.
> A: http://gnula.nu/

- easylistspanish/easylistspanish_specific_block.txt
https://github.com/uBlockOrigin/uAssets/issues/1851
> A: http://gnula.biz/

- easylistspanish/easylistspanish_specific_hide.txt
fix
* https://github.com/easylist/easylistspanish/commit/007d0f586d868376e929e182fe0e77359740c837
* https://forums.lanik.us/viewtopic.php?p=134911#p134911
> A: http://www.eleconomista.es/economia/noticias/9058724/04/18/Los.html

- easylistspanish/easylistspanish_general_block.txt
https://forums.lanik.us/viewtopic.php?p=135940#p135940
> A: https://puromarketing.com/

- easylistspanish/easylistspanish_specific_block.txt
https://forums.lanik.us/viewtopic.php?f=103&t=40867
> A: http://www.enderrock.cat/

- easylistspanish/easylistspanish_specific_hide.txt
https://forums.lanik.us/viewtopic.php?p=137379#p137379
> A: https://eldia.es/

- easylistspanish/easylistspanish_adservers.txt
`http://live.demand.supply/up.js`
> A: http://www.amigaironica.es/

- easylistspanish/easylistspanish_general_block.txt
e.g.
https://forums.lanik.us/viewtopic.php?p=107007&hilit=adn+zone#p107007
https://forums.lanik.us/viewtopic.php?p=136415&hilit=adn+zone#p136415
https://github.com/uBlockOrigin/uAssets/issues/1941
> A: (NSFW) https://porn.es/

- easylistspanish/easylistspanish_specific_block.txt
https://forums.lanik.us/viewtopic.php?f=103&t=42582
> A: https://www.darkstone.es/

- easylistspanish/easylistspanish_specific_block.txt
A: https://lineassobrearte.com/
> A: https://lineassobrearte.com/

- easylistspanish/easylistspanish_whitelist.txt
https://forums.lanik.us/viewtopic.php?f=103&t=43127
> P: https://www.autopista.es/automercado/

- easylistspanish/easylistspanish_thirdparty.txt
https://forums.lanik.us/viewtopic.php?f=103&t=43449
> A: https://keysbrasil.blogspot.com/

- easylistspanish/easylistspanish_specific_block.txt
> A:tumangaonline.uno

- easylistspanish/easylistspanish_specific_block_popup.txt
Blocking PopUp on mejortorrentt.net
> A:mejortorrentt.net

- easylistspanish/easylistspanish_specific_block_popup.txt
> A:zonarutoppuden.com

- easylistspanish/easylistspanish_whitelist.txt
> A: animeflv.net

- easylistspanish/easylistspanish_specific_block_popup.txt
Blocking Popup from video iframe
> A: hdfull.io

- easylistspanish/easylistspanish_specific_block_popup.txt
Blocking popup from video player
> A: estrenos10.com

- easylistspanish/easylistspanish_adservers_popup.txt
- easylistspanish/easylistspanish_specific_block.txt
- easylistspanish/easylistspanish_specific_block_popup.txt
- easylistspanish/easylistspanish_specific_hide.txt
Blocking Popups from video options and hidding ad
> A: pelispedia.nu

- easylistspanish/easylistspanish_specific_hide.txt
> A: noticiacristiana.com

- easylistspanish/easylistspanish_specific_block.txt
> A: animefenix.com

- easylistspanish/easylistspanish_specific_block.txt
- easylistspanish/easylistspanish_specific_hide.txt
Blocking ad script and hiding ad
> A: series24.me

- easylistspanish/easylistspanish_specific_hide.txt
> A: jkanime.net

- easylistspanish/easylistspanish_specific_hide.txt
Hiding Taboola ads to third-party sites
> A: sport.es

- easylistspanish/easylistspanish_adservers.txt
Blocking requests to ad servers
> A: fiuxy.es

- easylistspanish/easylistspanish_specific_hide.txt
> A: animeblix.com

- easylistspanish/easylistspanish_specific_block.txt
- easylistspanish/easylistspanish_specific_hide.txt
Blocking background image ad and hiding link element
> A: esportmaniacos.com

- easylistspanish/easylistspanish_specific_block.txt
> A: mejortorrentt.net

- easylistspanish/easylistspanish_specific_hide.txt
> A: planv.com.ec

- easylistspanish/easylistspanish_adservers.txt
> A: gamestorrents.nu

- easylistspanish/easylistspanish_specific_hide.txt
> A: https://blog.desdelinux.net/

- easylistspanish/easylistspanish_specific_hide.txt
To block ads on the right side
> A: https://www.somosjuarez.com/

- easylistspanish/easylistspanish_specific_block.txt
A: https://www.notebookcheck.org/
> A: https://www.notebookcheck.org/

- easylistspanish/easylistspanish_specific_block.txt
> A: https://www.elsoldemexico.com.mx/

- easylistspanish/easylistspanish_specific_hide.txt
Unblocked empty space on top of `https://www.autoscout24.es/lst/?sort=standard&desc=0&ustate=N%2CU&size=20&page=1&cy=E&atype=C&`
> A: https://www.autoscout24.es/lst/?sort=standard&desc=0&ustate=N%2CU&size=20&page=1&cy=E&atype=C&

- easylistspanish/easylistspanish_specific_block.txt
To block ads on the top and the right side
> A: https://www.elsiglodetorreon.com.mx/

- easylistspanish/easylistspanish_specific_hide.txt
Several unblocked empty spaces in  `https://www.fichajes.com/`
> A: https://www.fichajes.com/

- easylistspanish/easylistspanish_specific_block.txt
Add filter: `/popup-maker/$script,domain=diariotextual.com` to block fully popup image and fix scrolling issue on the page.
> A: diariotextual.com

- easylistspanish/easylistspanish_specific_hide.txt
Unblocked space on top of page.
> A: https://www.astrologiaenlinea.com/es/Index.asp

- easylistspanish/easylistspanish_adservers.txt
@jabonsolo I'm adding filter: `||solanoswajang.com^$third-party` to block popup message on [lectuepubgratis.com](https://lectuepubgratis.com)
> A: https://lectuepubgratis.com

- easylistspanish/easylistspanish_adservers.txt
Filter: `||educedsteeped.com^$third-party` to block popup message on monoschinos2.com
> A: https://monoschinos2.com/

- easylistspanish/easylistspanish_specific_hide.txt
Unblocked empty spaces in `https://www.europa-agricola.es/tractores-agricolas-usados/7-123/anuncios-tractores-agricolas.html`
> A: https://www.europa-agricola.es/tractores-agricolas-usados/7-123/anuncios-tractores-agricolas.html

- easylistspanish/easylistspanish_specific_hide.txt
> A: caracoltv.com

- easylistspanish/easylistspanish_specific_hide.txt
filter to hide placeholders on [poki.com](https://poki.com/)
`poki.com##div[class^="Advertisement__AdvertisementContainer"]`
> A: poki.com

- easylistspanish/easylistspanish_adservers.txt
Block ads on [tarjetarojatvonline](https://www.tarjetarojatvonline.sx/)
`||mynheerpuller.com^$third-party` - on the main page
`||dogiedimepupae.com^$third-party` - on some subpages
> A: tarjetarojatvonline.sx

- easylistspanish/easylistspanish_adservers_popup.txt
Block redirect popups on [pelisplushd.net](https://pelisplushd.net/pelicula/invasion-cosmica)
Steps to reproduce:
Select **SB Fast** and **Upload** server options and click on the play button.
> A: pelisplushd.net

- easylistspanish/easylistspanish_adservers_popup.txt
Block redirect popups on [pelispop.me](https://pelispop.me/escape-room-2-online-latino/)
**Steps to reproduce:**
OR click on the website logo
Select server **OPCIÓN 3** and click on the play button
> A: pelispop.me

- easylistspanish/easylistspanish_specific_hide.txt
Filters for all the Placeholders (Header, right side and footer) at [areajugones](https://areajugones.sport.es/).
Proposed filter: `areajugones.sport.es##.publicidad`
Explanation: It will block everything related to ads (parents and child's without blocking any content (18 matches) )
Screenshot (example of placeholder):
> A: areajugones.sport.es

- easylistspanish/easylistspanish_specific_block.txt
- easylistspanish_adult/adult_specific_hide.txt
Filter for blocking and hiding ads and ad text on [chaty](https://www.chaty.es/contacto.html) [NSFW]
Blocking filter (the text remains after all) : `||static.javhd.com^$third-party`
Hiding filter for the text: `##h2[style^="color:red;font-size:20px!important"]`
Screenshot:
> A: chaty.es [NSFW]

- easylistspanish/easylistspanish_specific_block.txt
Filter to block script loads (after clicking at anything) on [pelismaraton](https://pelismaraton.com/)
Proposed filter: `||streetcoddiffident.com^$script,third-party`
Screenshot:
> A: pelismaraton.com

- easylistspanish/easylistspanish_specific_block.txt
Filter for blocking the script responsible for popup messages at [entrepelis](https://entrepelis.org/)
Proposed filter: ||octanmystes.com^$script
Screenshot:
> A: entrepelis.org

- easylistspanish/easylistspanish_specific_hide.txt
Filter for hiding ad banner at [rewisor](https://www.rewisor.com/)
Proposed filter: `rewisor.com##.banner-h`
Screenshot:
> A: rewisor.com

- easylistspanish/easylistspanish_adservers.txt
FIlter for blocking adserver respondible for ads at the following webpage [doramasflix](https://doramasflix.vip/episodios-online-gratis/squid-game-capitulo-1/)
Filter proposed: ||sunwardamoraic.com^$third-party
Screenshot: [IR - Screenshot](https://reports.adblockplus.org/611fdb51-0a0b-448e-9dd6-c665c935ee61#tab=screenshot)
> A: doramasflix.vip

- easylistspanish/easylistspanish_specific_hide.txt
Filter for hiding placeholders at [puupnewsapp - content subs](https://www.puupnewsapp.com/internet-download-manager-for-chrome/)
Proposed filter for classes code-block-1, code-block-2, code-block-3: 
`puupnewsapp.com##[class*="code-block-"]`
Screenshot:
> A: puupnewsapp.com

- easylistspanish/easylistspanish_specific_block.txt
https://alicantetoday.com/v2/AlicanteToday/index
> alicantetoday.com

- easylistspanish/easylistspanish_specific_block.txt
Updated filter for the Amazon text ads.
> M: https://www.notebookcheck.org/

- easylistspanish/easylistspanish_specific_hide.txt
Hide ads at https://www.carrefour.es/supermercado/drinks/beer/light-beer/cat20189/c?ic_source=portal-y-corporativo&ic_medium=menu-links&ic_content=ns
**Steps to reproduce:**
Search for class: `.rm-format` 
They link to `b.nl.eu.criteo.com/rm?rm_`
**Has Patrocinado label**
**Has `aria-label="advertisement"`**
Suggested filter: `carrefour.es##.rm-format`
> A: https://www.carrefour.es

- easylistspanish/easylistspanish_specific_hide.txt
Reverts easylist/easylistspanish#257
> Revert "A: https://www.carrefour.es"

- easylistspanish/easylistspanish_specific_hide.txt
Hide ad overlay and ad close button on [razon.com.mx](https://www.razon.com.mx/)
_Did not add `##.stickyad-close` as it would hide the close button only._
Reference https://github.com/easylist/easylist/commit/49ecc17
> A: https://www.razon.com.mx/

- easylistspanish/easylistspanish_specific_block.txt
.fun^$domain=skidrowreloaded.com
> del deprecated filter skidrowreloaded.com

- easylistspanish/easylistspanish_specific_block.txt
||aimdigital.com.ar/wp-content/uploads/*.gif
||aimdigital.com.ar/wp-content/uploads/2017/07/adepa-AIM.jpg
||aimdigital.com.ar/wp-content/uploads/2017/08/300_x_250_min_de_turismo1.jpg
||aimdigital.com.ar/wp-content/uploads/2017/10/01-*-TU-PARTE-BOLSAS.jpg
||aimdigital.com.ar/wp-content/uploads/2017/10/enersa-logo-publi.jpg
||aimdigital.com.ar/wp-content/uploads/2017/10/salud.jpg
||aimdigital.com.ar/wp-content/uploads/2017/10/turismo.jpg
> del deprecated filters aimdigital.com.ar

- easylistspanish/easylistspanish_specific_block.txt
||aica.org/publi*.html?t=
||aica.org/publi/
> del deprecated filters aica.org

- easylistspanish/easylistspanish_specific_hide.txt
> A: animated ad on merca20.com

- easylistspanish/easylistspanish_specific_block.txt
||19640noticias.com/wp-content/uploads/2017/03/200x200_OK_-1-Copiar.jpg
||19640noticias.com/wp-content/uploads/2017/03/Banner-Institucional-300x200-Copiar.jpg
||19640noticias.com/wp-content/uploads/2017/03/Veronica-Gonzalez-Copiar-Copiar.jpg
||19640noticias.com/wp-content/uploads/2017/04/283x321.gif
> del deprecated filters for 19640noticias.com

- easylistspanish/easylistspanish_specific_block.txt
||imagensn.com/images/2016/09/02/uploaded-banner-300.jpg
||imagensn.com/images/2016/09/02/uploaded-banner-728.jpg
||imagensn.com/images/2016/12/07/dedicados.jpg
||imagensn.com/images/2016/12/07/servidores.jpg
> del deprecated filter

- easylistspanish/easylistspanish_specific_block.txt
||diariotextual.com/images/articulos-2014/*.gif
||diariotextual.com/images/articulos-2014/*banner
> del deprecated filter diariotextual.com

- easylistspanish/easylistspanish_specific_block.txt
||diariodelaribera.org/images/banners/
||diariodelaribera.org/images/stories/banners2015/noviembre_2015/
||diariodelaribera.org/images/stories/banners2015/octubre_2015/
> del deprecated filter diariodelaribera.org

- easylistspanish/easylistspanish_specific_block.txt
||mundodeportivo.com/r/GODO/MD/p3/Canales/Imagenes/*/lacaixa.jpg
||mundodeportivo.com/r/GODO/MD/p3/Canales/Imagenes/*/runedia.jpg
||mundodeportivo.com/r/GODO/MD/p3/Canales/Imagenes/2015/02/06/
||mundodeportivo.com/r/GODO/MD/p3/ContraPortada/Imagenes/*/img_cduart_*_imagenes_md_otras_fuentes_bmw_*.jpg
> del deprecated filter mundodeportivo.com

- easylistspanish/easylistspanish_specific_block.txt
||elperiodico.cl/wp-content/uploads/2016/05/diariouchile.swf
> del deprecated filter elperiodico.cl

- easylistspanish/easylistspanish_specific_block.txt
||planbnoticias.com.ar/pb/wp-content/uploads/2017/03/IMG_0762.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/05/gif-*-de-socios.gif ||planbnoticias.com.ar/pb/wp-content/uploads/2017/05/Pauta2017-300x300.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/08/daniel-movilero5.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/09/tiene-sentido-4.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/09/yaco-2.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/10/PATRA-GRANDE.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/10/rlt-1.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/11/camioneros-baner.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/11/catrilo-muni.jpg ||planbnoticias.com.ar/pb/wp-content/uploads/2017/11/red-habita2.jpg
> del deprecated filters planbnoticias.com.ar

- easylistspanish/easylistspanish_specific_block.txt
||pescare.com.ar/banners/
||pescare.com.ar/img/banner-top.jpg
||pescare.com.ar/wp-content/uploads/2015/10/bpg5.jpg ||pescare.com.ar/wp-content/uploads/2015/10/solimeno.jpg
> del deprecated filters pescare.com.ar

- easylistspanish/easylistspanish_specific_hide.txt
Hide center and side banners at https://www.cinelibreonline.com/
> A: https://www.cinelibreonline.com/

- easylistspanish/easylistspanish_specific_hide.txt
https://norteenlinea.com/
https://thaderclub.com/
https://arquimaster.com.ar/
https://periodismokosher.com.ar/
> A: Hide banners

- easylistspanish/easylistspanish_specific_hide.txt
Hide banners at https://www.noticiasdegipuzkoa.eus/balonmano/2023/02/09/benardo-garcia-presidente-bidasoa-entrevista-6421645.html
> A: https://www.noticiasdegipuzkoa.eus/

- easylistspanish/easylistspanish_specific_block.txt
https://www.rojadirectaenvivo.fr/2023/super-bowl-lvii-eagles-vs-chiefs-en-vivo.php
> https://www.rojadirectaenvivo.fr

- easylistspanish/easylistspanish_specific_hide.txt
Bottom placeholder at https://www.elcorreogallego.es/
> A: https://www.elcorreogallego.es/

- easylistspanish/easylistspanish_specific_block.txt
Hi, please add this filter to block the redirections on the page, as you can see into the screenshot, this script is just rendering `donutfulfilheard.com` which is an ad server.  Thank you
> A:`cuevana.cloud`

- easylistspanish/easylistspanish_specific_hide.txt
Hi could you please add this domain to the existing filter there is an empty placeholder left after the ads are removed. 
Thank you
> A: `revistacromos.com.co`

- easylistspanish/easylistspanish_specific_block.txt
Stops Popups on 'www.rojadirectatv.ws'
> A:`www.rojadirectatv.ws`

- easylistspanish/easylistspanish_specific_hide.txt
Left side advertising banners:
Thanks
> A:`agencianova.com`

- easylistspanish/easylistspanish_specific_hide.txt
hi please add the domain to the existing filter, there are banners on the page:
> A:`miradiols.cl`

- easylistspanish/easylistspanish_specific_hide.txt
hi could you please add this filter to the list there is a banner at the bottom of the page.
> A:`diariobitcoin.com`

- easylistspanish/easylistspanish_specific_hide.txt
Hi please add this domain to the existing filter there is a right side column with ads:
thank you
> A:`cultoro.es`

- easylistspanish/easylistspanish_specific_hide.txt
Ads widget on the article page for example[ here](https://www.prensa.com/unidad-investigativa/bukele-desvio-un-prestamo-del-bcie-para-convertir-a-bitcoin-en-moneda-nacional/)
Thank you
> A:`prensa.com`

- easylistspanish/easylistspanish_specific_hide.txt
banner ad at top of page
one side bar ad on the right
> A: https://meneame.net/
